var classes = [
    {
        "name": "Hal\\Report\\Html\\Reporter",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "renderPage",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTrend",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 14,
        "externals": [
            "Hal\\Application\\Config\\Config",
            "Hal\\Component\\Output\\Output",
            "Hal\\Metric\\Metrics",
            "Hal\\Metric\\Consolidated",
            "Hal\\Metric\\Consolidated"
        ],
        "lcom": 1,
        "length": 360,
        "vocabulary": 90,
        "volume": 2337.07,
        "difficulty": 12.54,
        "effort": 29298.84,
        "level": 0.08,
        "bugs": 0.78,
        "time": 1628,
        "intelligentContent": 186.42,
        "number_operators": 103,
        "number_operands": 257,
        "number_operators_unique": 8,
        "number_operands_unique": 82,
        "cloc": 30,
        "loc": 151,
        "lloc": 124,
        "mi": 60.71,
        "mIwoC": 28.86,
        "commentWeight": 31.85,
        "kanDefect": 1.36,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.68,
        "relativeSystemComplexity": 81.68,
        "totalStructuralComplexity": 324,
        "totalDataComplexity": 2.7,
        "totalSystemComplexity": 326.7,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Report\\Violations\\Xml\\Reporter",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 7,
        "externals": [
            "Hal\\Application\\Config\\Config",
            "Hal\\Component\\Output\\Output",
            "Hal\\Metric\\Metrics",
            "DOMDocument"
        ],
        "lcom": 1,
        "length": 96,
        "vocabulary": 40,
        "volume": 510.91,
        "difficulty": 5.71,
        "effort": 2919.46,
        "level": 0.18,
        "bugs": 0.17,
        "time": 162,
        "intelligentContent": 89.41,
        "number_operators": 16,
        "number_operands": 80,
        "number_operators_unique": 5,
        "number_operands_unique": 35,
        "cloc": 15,
        "loc": 61,
        "lloc": 47,
        "mi": 78.36,
        "mIwoC": 43.62,
        "commentWeight": 34.74,
        "kanDefect": 0.75,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.23,
        "relativeSystemComplexity": 100.23,
        "totalStructuralComplexity": 200,
        "totalDataComplexity": 0.45,
        "totalSystemComplexity": 200.45,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Report\\Cli\\Reporter",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 9,
        "externals": [
            "Hal\\Application\\Config\\Config",
            "Hal\\Component\\Output\\Output",
            "Hal\\Metric\\Metrics",
            "Hal\\Metric\\Consolidated"
        ],
        "lcom": 1,
        "length": 168,
        "vocabulary": 68,
        "volume": 1022.69,
        "difficulty": 7.75,
        "effort": 7921.69,
        "level": 0.13,
        "bugs": 0.34,
        "time": 440,
        "intelligentContent": 132.03,
        "number_operators": 33,
        "number_operands": 135,
        "number_operators_unique": 7,
        "number_operands_unique": 61,
        "cloc": 14,
        "loc": 105,
        "lloc": 85,
        "mi": 62.43,
        "mIwoC": 35.63,
        "commentWeight": 26.8,
        "kanDefect": 1.03,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.36,
        "relativeSystemComplexity": 36.36,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0.71,
        "totalSystemComplexity": 72.71,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Metric\\Consolidated",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAvg",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSum",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getClasses",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFiles",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getProject",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 5,
        "nbMethodsSetters": 0,
        "ccn": 9,
        "externals": [
            "Hal\\Metric\\Metrics"
        ],
        "lcom": 1,
        "length": 181,
        "vocabulary": 53,
        "volume": 1036.75,
        "difficulty": 10.5,
        "effort": 10885.91,
        "level": 0.1,
        "bugs": 0.35,
        "time": 605,
        "intelligentContent": 98.74,
        "number_operators": 43,
        "number_operands": 138,
        "number_operators_unique": 7,
        "number_operands_unique": 46,
        "cloc": 37,
        "loc": 123,
        "lloc": 86,
        "mi": 73.03,
        "mIwoC": 35.47,
        "commentWeight": 37.55,
        "kanDefect": 1.67,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.29,
        "relativeSystemComplexity": 10.29,
        "totalStructuralComplexity": 54,
        "totalDataComplexity": 7.75,
        "totalSystemComplexity": 61.75,
        "pageRank": 0.01,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Metric\\InterfaceMetric",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Hal\\Metric\\ClassMetric"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Metric\\FunctionMetric",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Hal\\Metric\\Metric",
            "JsonSerializable"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 4,
        "efferentCoupling": 2,
        "instability": 0.33,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Metric\\FileMetric",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Hal\\Metric\\Metric",
            "JsonSerializable"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Metric\\Metrics",
        "interface": false,
        "methods": [
            {
                "name": "attach",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "has",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "all",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "jsonSerialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "JsonSerializable"
        ],
        "lcom": 1,
        "length": 21,
        "vocabulary": 5,
        "volume": 48.76,
        "difficulty": 5,
        "effort": 243.8,
        "level": 0.2,
        "bugs": 0.02,
        "time": 14,
        "intelligentContent": 9.75,
        "number_operators": 6,
        "number_operands": 15,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 25,
        "loc": 51,
        "lloc": 26,
        "mi": 101.39,
        "mIwoC": 57.18,
        "commentWeight": 44.21,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.4,
        "relativeSystemComplexity": 10.4,
        "totalStructuralComplexity": 45,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 52,
        "pageRank": 0.02,
        "afferentCoupling": 18,
        "efferentCoupling": 1,
        "instability": 0.05,
        "numberOfUnitTests": 12,
        "violations": {}
    },
    {
        "name": "Hal\\Metric\\ProjectMetric",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Hal\\Metric\\Metric",
            "JsonSerializable"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Metric\\Helper\\RoleOfMethodDetector",
        "interface": false,
        "methods": [
            {
                "name": "detects",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "externals": [],
        "lcom": 1,
        "length": 52,
        "vocabulary": 21,
        "volume": 228.4,
        "difficulty": 8.75,
        "effort": 1998.5,
        "level": 0.11,
        "bugs": 0.08,
        "time": 111,
        "intelligentContent": 26.1,
        "number_operators": 17,
        "number_operands": 35,
        "number_operators_unique": 7,
        "number_operands_unique": 14,
        "cloc": 15,
        "loc": 44,
        "lloc": 29,
        "mi": 90.35,
        "mIwoC": 51.05,
        "commentWeight": 39.31,
        "kanDefect": 0.66,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 6,
        "relativeSystemComplexity": 6,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 6,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "numberOfUnitTests": 1,
        "violations": {}
    },
    {
        "name": "Hal\\Metric\\Class_\\Component\\MaintainabilityIndexVisitor",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "leaveNode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 10,
        "externals": [
            "PhpParser\\NodeVisitorAbstract",
            "Hal\\Metric\\Metrics",
            "PhpParser\\Node",
            "Hal\\Metric\\FunctionMetric",
            "LogicException",
            "LogicException",
            "LogicException",
            "LogicException",
            "LogicException"
        ],
        "lcom": 1,
        "length": 111,
        "vocabulary": 36,
        "volume": 573.86,
        "difficulty": 10.14,
        "effort": 5820.6,
        "level": 0.1,
        "bugs": 0.19,
        "time": 323,
        "intelligentContent": 56.58,
        "number_operators": 40,
        "number_operands": 71,
        "number_operators_unique": 8,
        "number_operands_unique": 28,
        "cloc": 31,
        "loc": 77,
        "lloc": 46,
        "mi": 84.67,
        "mIwoC": 43.07,
        "commentWeight": 41.61,
        "kanDefect": 0.78,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.2,
        "relativeSystemComplexity": 16.2,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 0.4,
        "totalSystemComplexity": 32.4,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 9,
        "instability": 0.9,
        "numberOfUnitTests": 1,
        "violations": {}
    },
    {
        "name": "Hal\\Metric\\Class_\\Coupling\\ExternalsVisitor",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "leaveNode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 20,
        "externals": [
            "PhpParser\\NodeVisitorAbstract",
            "Hal\\Metric\\Metrics",
            "PhpParser\\Node"
        ],
        "lcom": 1,
        "length": 102,
        "vocabulary": 25,
        "volume": 473.67,
        "difficulty": 14.97,
        "effort": 7091.94,
        "level": 0.07,
        "bugs": 0.16,
        "time": 394,
        "intelligentContent": 31.64,
        "number_operators": 25,
        "number_operands": 77,
        "number_operators_unique": 7,
        "number_operands_unique": 18,
        "cloc": 27,
        "loc": 102,
        "lloc": 75,
        "mi": 73.44,
        "mIwoC": 37.67,
        "commentWeight": 35.77,
        "kanDefect": 2.66,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.17,
        "relativeSystemComplexity": 25.17,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 50.33,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "numberOfUnitTests": 2,
        "violations": {}
    },
    {
        "name": "Hal\\Metric\\Class_\\Text\\HalsteadVisitor",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "leaveNode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "externals": [
            "PhpParser\\NodeVisitorAbstract",
            "Hal\\Metric\\Metrics",
            "PhpParser\\Node",
            "Hal\\Metric\\FunctionMetric"
        ],
        "lcom": 1,
        "length": 218,
        "vocabulary": 50,
        "volume": 1230.36,
        "difficulty": 11.97,
        "effort": 14721.41,
        "level": 0.08,
        "bugs": 0.41,
        "time": 818,
        "intelligentContent": 102.83,
        "number_operators": 71,
        "number_operands": 147,
        "number_operators_unique": 7,
        "number_operands_unique": 43,
        "cloc": 29,
        "loc": 88,
        "lloc": 59,
        "mi": 78.03,
        "mIwoC": 39.2,
        "commentWeight": 38.83,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.2,
        "relativeSystemComplexity": 16.2,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 0.4,
        "totalSystemComplexity": 32.4,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "numberOfUnitTests": 1,
        "violations": {}
    },
    {
        "name": "Hal\\Metric\\Class_\\Text\\LengthVisitor",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "leaveNode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 5,
        "externals": [
            "PhpParser\\NodeVisitorAbstract",
            "Hal\\Metric\\Metrics",
            "PhpParser\\Node",
            "Hal\\Metric\\FunctionMetric",
            "PhpParser\\PrettyPrinter\\Standard"
        ],
        "lcom": 1,
        "length": 80,
        "vocabulary": 25,
        "volume": 371.51,
        "difficulty": 7.75,
        "effort": 2879.19,
        "level": 0.13,
        "bugs": 0.12,
        "time": 160,
        "intelligentContent": 47.94,
        "number_operators": 18,
        "number_operands": 62,
        "number_operators_unique": 5,
        "number_operands_unique": 20,
        "cloc": 20,
        "loc": 55,
        "lloc": 36,
        "mi": 87.59,
        "mIwoC": 47.38,
        "commentWeight": 40.21,
        "kanDefect": 0.59,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.17,
        "relativeSystemComplexity": 25.17,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 50.33,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "numberOfUnitTests": 1,
        "violations": {}
    },
    {
        "name": "Hal\\Metric\\Class_\\Complexity\\KanDefectVisitor",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "leaveNode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "externals": [
            "PhpParser\\NodeVisitorAbstract",
            "Hal\\Metric\\Metrics",
            "PhpParser\\Node"
        ],
        "lcom": 1,
        "length": 50,
        "vocabulary": 21,
        "volume": 219.62,
        "difficulty": 7,
        "effort": 1537.31,
        "level": 0.14,
        "bugs": 0.07,
        "time": 85,
        "intelligentContent": 31.37,
        "number_operators": 15,
        "number_operands": 35,
        "number_operators_unique": 6,
        "number_operands_unique": 15,
        "cloc": 15,
        "loc": 48,
        "lloc": 33,
        "mi": 88.3,
        "mIwoC": 50.21,
        "commentWeight": 38.09,
        "kanDefect": 0.44,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 9.25,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 18.5,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "numberOfUnitTests": 1,
        "violations": {}
    },
    {
        "name": "Hal\\Metric\\Class_\\Complexity\\CyclomaticComplexityVisitor",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "leaveNode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "externals": [
            "PhpParser\\NodeVisitorAbstract",
            "Hal\\Metric\\Metrics",
            "PhpParser\\Node"
        ],
        "lcom": 1,
        "length": 68,
        "vocabulary": 19,
        "volume": 288.86,
        "difficulty": 18.91,
        "effort": 5462.06,
        "level": 0.05,
        "bugs": 0.1,
        "time": 303,
        "intelligentContent": 15.28,
        "number_operators": 16,
        "number_operands": 52,
        "number_operators_unique": 8,
        "number_operands_unique": 11,
        "cloc": 27,
        "loc": 80,
        "lloc": 53,
        "mi": 83.79,
        "mIwoC": 44.62,
        "commentWeight": 39.17,
        "kanDefect": 1.04,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 9.5,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 19,
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "numberOfUnitTests": 1,
        "violations": {}
    },
    {
        "name": "Hal\\Metric\\Class_\\ClassEnumVisitor",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "leaveNode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 8,
        "externals": [
            "PhpParser\\NodeVisitorAbstract",
            "Hal\\Metric\\Metrics",
            "PhpParser\\Node",
            "Hal\\Metric\\InterfaceMetric",
            "Hal\\Metric\\ClassMetric",
            "Hal\\Metric\\Helper\\RoleOfMethodDetector",
            "Hal\\Metric\\FunctionMetric"
        ],
        "lcom": 1,
        "length": 113,
        "vocabulary": 35,
        "volume": 579.61,
        "difficulty": 12.59,
        "effort": 7298.78,
        "level": 0.08,
        "bugs": 0.19,
        "time": 405,
        "intelligentContent": 46.03,
        "number_operators": 28,
        "number_operands": 85,
        "number_operators_unique": 8,
        "number_operands_unique": 27,
        "cloc": 8,
        "loc": 73,
        "lloc": 65,
        "mi": 64.56,
        "mIwoC": 40.03,
        "commentWeight": 24.53,
        "kanDefect": 1.09,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 49.13,
        "totalStructuralComplexity": 98,
        "totalDataComplexity": 0.25,
        "totalSystemComplexity": 98.25,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 7,
        "instability": 0.88,
        "numberOfUnitTests": 11,
        "violations": {}
    },
    {
        "name": "Hal\\Metric\\Class_\\Structural\\SystemComplexityVisitor",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "leaveNode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "externals": [
            "PhpParser\\NodeVisitorAbstract",
            "Hal\\Metric\\Metrics",
            "PhpParser\\Node"
        ],
        "lcom": 1,
        "length": 98,
        "vocabulary": 27,
        "volume": 465.98,
        "difficulty": 8.3,
        "effort": 3865.51,
        "level": 0.12,
        "bugs": 0.16,
        "time": 215,
        "intelligentContent": 56.17,
        "number_operators": 25,
        "number_operands": 73,
        "number_operators_unique": 5,
        "number_operands_unique": 22,
        "cloc": 23,
        "loc": 63,
        "lloc": 40,
        "mi": 86.09,
        "mIwoC": 45.83,
        "commentWeight": 40.26,
        "kanDefect": 0.74,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 9.25,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 18.5,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "numberOfUnitTests": 1,
        "violations": {}
    },
    {
        "name": "Hal\\Metric\\Class_\\Structural\\LcomVisitor",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "leaveNode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "traverse",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 8,
        "externals": [
            "PhpParser\\NodeVisitorAbstract",
            "Hal\\Metric\\Metrics",
            "PhpParser\\Node",
            "Hal\\Component\\Tree\\Graph",
            "Hal\\Component\\Tree\\Node",
            "Hal\\Component\\Tree\\Node",
            "Hal\\Component\\Tree\\Node",
            "Hal\\Component\\Tree\\Node"
        ],
        "lcom": 1,
        "length": 111,
        "vocabulary": 23,
        "volume": 502.12,
        "difficulty": 20.53,
        "effort": 10310.1,
        "level": 0.05,
        "bugs": 0.17,
        "time": 573,
        "intelligentContent": 24.45,
        "number_operators": 34,
        "number_operands": 77,
        "number_operators_unique": 8,
        "number_operands_unique": 15,
        "cloc": 27,
        "loc": 89,
        "lloc": 62,
        "mi": 78.59,
        "mIwoC": 40.91,
        "commentWeight": 37.67,
        "kanDefect": 1.47,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 81.5,
        "totalStructuralComplexity": 243,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 244.5,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 8,
        "instability": 0.89,
        "numberOfUnitTests": 1,
        "violations": {}
    },
    {
        "name": "Hal\\Metric\\System\\Changes\\GitChanges",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "calculate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "doesThisFileShouldBeCounted",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 14,
        "externals": [
            "Hal\\Application\\Config\\Config",
            "Hal\\Metric\\Metrics",
            "Hal\\Application\\Config\\ConfigException",
            "DateTime",
            "Hal\\Metric\\ProjectMetric",
            "Hal\\Metric\\FileMetric"
        ],
        "lcom": 1,
        "length": 256,
        "vocabulary": 49,
        "volume": 1437.37,
        "difficulty": 16.17,
        "effort": 23237.41,
        "level": 0.06,
        "bugs": 0.48,
        "time": 1291,
        "intelligentContent": 88.91,
        "number_operators": 62,
        "number_operands": 194,
        "number_operators_unique": 7,
        "number_operands_unique": 42,
        "cloc": 36,
        "loc": 142,
        "lloc": 106,
        "mi": 66.99,
        "mIwoC": 31.83,
        "commentWeight": 35.17,
        "kanDefect": 1.82,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.54,
        "relativeSystemComplexity": 49.54,
        "totalStructuralComplexity": 147,
        "totalDataComplexity": 1.63,
        "totalSystemComplexity": 148.63,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 6,
        "instability": 0.86,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Metric\\System\\Coupling\\PageRank",
        "interface": false,
        "methods": [
            {
                "name": "calculate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "calculatePageRank",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 12,
        "externals": [
            "Hal\\Metric\\Metrics"
        ],
        "lcom": 1,
        "length": 136,
        "vocabulary": 40,
        "volume": 723.78,
        "difficulty": 24.31,
        "effort": 17598.63,
        "level": 0.04,
        "bugs": 0.24,
        "time": 978,
        "intelligentContent": 29.77,
        "number_operators": 35,
        "number_operands": 101,
        "number_operators_unique": 13,
        "number_operands_unique": 27,
        "cloc": 20,
        "loc": 75,
        "lloc": 55,
        "mi": 76.27,
        "mIwoC": 40.4,
        "commentWeight": 35.87,
        "kanDefect": 2.13,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 16.5,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 33,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Metric\\System\\Coupling\\Coupling",
        "interface": false,
        "methods": [
            {
                "name": "calculate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 14,
        "externals": [
            "Hal\\Metric\\Metrics",
            "Hal\\Component\\Tree\\Graph",
            "Hal\\Component\\Tree\\Node",
            "Hal\\Component\\Tree\\Node"
        ],
        "lcom": 1,
        "length": 84,
        "vocabulary": 23,
        "volume": 379.98,
        "difficulty": 11.12,
        "effort": 4224.47,
        "level": 0.09,
        "bugs": 0.13,
        "time": 235,
        "intelligentContent": 34.18,
        "number_operators": 21,
        "number_operands": 63,
        "number_operators_unique": 6,
        "number_operands_unique": 17,
        "cloc": 12,
        "loc": 56,
        "lloc": 44,
        "mi": 77.06,
        "mIwoC": 44.2,
        "commentWeight": 32.86,
        "kanDefect": 1.56,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.09,
        "relativeSystemComplexity": 100.09,
        "totalStructuralComplexity": 100,
        "totalDataComplexity": 0.09,
        "totalSystemComplexity": 100.09,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Metric\\ClassMetric",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Hal\\Metric\\Metric",
            "JsonSerializable"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Component\\Ast\\NodeTraverser",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "traverseArray",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 6,
        "externals": [
            "PhpParser\\NodeTraverser",
            "parent"
        ],
        "lcom": 1,
        "length": 93,
        "vocabulary": 19,
        "volume": 395.06,
        "difficulty": 17.79,
        "effort": 7028.73,
        "level": 0.06,
        "bugs": 0.13,
        "time": 390,
        "intelligentContent": 22.2,
        "number_operators": 32,
        "number_operands": 61,
        "number_operators_unique": 7,
        "number_operands_unique": 12,
        "cloc": 5,
        "loc": 65,
        "lloc": 60,
        "mi": 63.05,
        "mIwoC": 42.22,
        "commentWeight": 20.83,
        "kanDefect": 1.63,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.75,
        "relativeSystemComplexity": 25.75,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 51.5,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Component\\Output\\CliOutput",
        "interface": false,
        "methods": [
            {
                "name": "writeln",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "write",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "err",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clearln",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setQuietMode",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "ccn": 2,
        "externals": [
            "Hal\\Component\\Output\\Output"
        ],
        "lcom": 2,
        "length": 30,
        "vocabulary": 11,
        "volume": 103.78,
        "difficulty": 6.29,
        "effort": 652.35,
        "level": 0.16,
        "bugs": 0.03,
        "time": 36,
        "intelligentContent": 16.51,
        "number_operators": 8,
        "number_operands": 22,
        "number_operators_unique": 4,
        "number_operands_unique": 7,
        "cloc": 25,
        "loc": 54,
        "lloc": 31,
        "mi": 96.55,
        "mIwoC": 53.08,
        "commentWeight": 43.47,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.93,
        "relativeSystemComplexity": 5.93,
        "totalStructuralComplexity": 20,
        "totalDataComplexity": 9.67,
        "totalSystemComplexity": 29.67,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Component\\Output\\ProgressBar",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "start",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "advance",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasAnsi",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "externals": [
            "Hal\\Component\\Output\\Output"
        ],
        "lcom": 1,
        "length": 66,
        "vocabulary": 29,
        "volume": 320.63,
        "difficulty": 12.83,
        "effort": 4114.71,
        "level": 0.08,
        "bugs": 0.11,
        "time": 229,
        "intelligentContent": 24.98,
        "number_operators": 24,
        "number_operands": 42,
        "number_operators_unique": 11,
        "number_operands_unique": 18,
        "cloc": 40,
        "loc": 83,
        "lloc": 43,
        "mi": 90.27,
        "mIwoC": 46.28,
        "commentWeight": 43.99,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.6,
        "relativeSystemComplexity": 9.6,
        "totalStructuralComplexity": 45,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 48,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Component\\Issue\\Issuer",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "onError",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "enable",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "disable",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "terminate",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "log",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "set",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "clear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 7,
        "externals": [
            "Hal\\Component\\Output\\Output",
            "PhpParser\\PrettyPrinter\\Standard"
        ],
        "lcom": 3,
        "length": 123,
        "vocabulary": 49,
        "volume": 690.61,
        "difficulty": 6.77,
        "effort": 4673.66,
        "level": 0.15,
        "bugs": 0.23,
        "time": 260,
        "intelligentContent": 102.05,
        "number_operators": 26,
        "number_operands": 97,
        "number_operators_unique": 6,
        "number_operands_unique": 43,
        "cloc": 44,
        "loc": 152,
        "lloc": 95,
        "mi": 73.05,
        "mIwoC": 36.04,
        "commentWeight": 37.01,
        "kanDefect": 0.89,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1.48,
        "relativeSystemComplexity": 17.48,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 11.8,
        "totalSystemComplexity": 139.8,
        "pageRank": 0,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Component\\Tree\\Edge",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFrom",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTo",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "asString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Hal\\Component\\Tree\\Node",
            "Hal\\Component\\Tree\\Node"
        ],
        "lcom": 1,
        "length": 16,
        "vocabulary": 6,
        "volume": 41.36,
        "difficulty": 2.75,
        "effort": 113.74,
        "level": 0.36,
        "bugs": 0.01,
        "time": 6,
        "intelligentContent": 15.04,
        "number_operators": 5,
        "number_operands": 11,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 23,
        "loc": 47,
        "lloc": 24,
        "mi": 102.62,
        "mIwoC": 58.44,
        "commentWeight": 44.19,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.75,
        "relativeSystemComplexity": 2.75,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 11,
        "pageRank": 0.37,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "numberOfUnitTests": 1,
        "violations": {}
    },
    {
        "name": "Hal\\Component\\Tree\\Node",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getKey",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAdjacents",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getEdges",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addEdge",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getData",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setData",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 1,
        "ccn": 4,
        "externals": [
            "Hal\\Component\\Tree\\Edge"
        ],
        "lcom": 1,
        "length": 47,
        "vocabulary": 9,
        "volume": 148.99,
        "difficulty": 12.4,
        "effort": 1847.43,
        "level": 0.08,
        "bugs": 0.05,
        "time": 103,
        "intelligentContent": 12.02,
        "number_operators": 16,
        "number_operands": 31,
        "number_operators_unique": 4,
        "number_operands_unique": 5,
        "cloc": 40,
        "loc": 89,
        "lloc": 49,
        "mi": 90.46,
        "mIwoC": 47.38,
        "commentWeight": 43.08,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.64,
        "relativeSystemComplexity": 10.64,
        "totalStructuralComplexity": 63,
        "totalDataComplexity": 11.5,
        "totalSystemComplexity": 74.5,
        "pageRank": 0.35,
        "afferentCoupling": 13,
        "efferentCoupling": 1,
        "instability": 0.07,
        "numberOfUnitTests": 42,
        "violations": {}
    },
    {
        "name": "Hal\\Component\\Tree\\Graph",
        "interface": false,
        "methods": [
            {
                "name": "insert",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addEdge",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "asString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getEdges",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "has",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "count",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "all",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "ccn": 6,
        "externals": [
            "Countable",
            "Hal\\Component\\Tree\\Node",
            "Hal\\Component\\Tree\\GraphException",
            "Hal\\Component\\Tree\\Node",
            "Hal\\Component\\Tree\\Node",
            "Hal\\Component\\Tree\\GraphException",
            "Hal\\Component\\Tree\\GraphException",
            "Hal\\Component\\Tree\\Edge"
        ],
        "lcom": 1,
        "length": 67,
        "vocabulary": 16,
        "volume": 268,
        "difficulty": 8.5,
        "effort": 2278,
        "level": 0.12,
        "bugs": 0.09,
        "time": 127,
        "intelligentContent": 31.53,
        "number_operators": 16,
        "number_operands": 51,
        "number_operators_unique": 4,
        "number_operands_unique": 12,
        "cloc": 35,
        "loc": 94,
        "lloc": 59,
        "mi": 84.1,
        "mIwoC": 43.56,
        "commentWeight": 40.53,
        "kanDefect": 0.82,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 1.23,
        "relativeSystemComplexity": 37.23,
        "totalStructuralComplexity": 288,
        "totalDataComplexity": 9.86,
        "totalSystemComplexity": 297.86,
        "pageRank": 0.01,
        "afferentCoupling": 3,
        "efferentCoupling": 8,
        "instability": 0.73,
        "numberOfUnitTests": 10,
        "violations": {}
    },
    {
        "name": "Hal\\Component\\Tree\\Operator\\CycleDetector",
        "interface": false,
        "methods": [
            {
                "name": "isCyclic",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "detectCycle",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 9,
        "externals": [
            "Hal\\Component\\Tree\\Graph",
            "Hal\\Component\\Tree\\Node"
        ],
        "lcom": 1,
        "length": 64,
        "vocabulary": 12,
        "volume": 229.44,
        "difficulty": 14.29,
        "effort": 3277.68,
        "level": 0.07,
        "bugs": 0.08,
        "time": 182,
        "intelligentContent": 16.06,
        "number_operators": 24,
        "number_operands": 40,
        "number_operators_unique": 5,
        "number_operands_unique": 7,
        "cloc": 23,
        "loc": 64,
        "lloc": 41,
        "mi": 87.12,
        "mIwoC": 47.08,
        "commentWeight": 40.04,
        "kanDefect": 1.12,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.79,
        "relativeSystemComplexity": 36.79,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 1.57,
        "totalSystemComplexity": 73.57,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 4,
        "violations": {}
    },
    {
        "name": "Hal\\Component\\Tree\\GraphException",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "LogicException"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Component\\Tree\\HashMap",
        "interface": false,
        "methods": [
            {
                "name": "attach",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "has",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "count",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getIterator",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Countable",
            "IteratorAggregate",
            "Hal\\Component\\Tree\\Node",
            "ArrayIterator"
        ],
        "lcom": 1,
        "length": 21,
        "vocabulary": 5,
        "volume": 48.76,
        "difficulty": 5,
        "effort": 243.8,
        "level": 0.2,
        "bugs": 0.02,
        "time": 14,
        "intelligentContent": 9.75,
        "number_operators": 6,
        "number_operands": 15,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 21,
        "loc": 47,
        "lloc": 26,
        "mi": 100.19,
        "mIwoC": 57.18,
        "commentWeight": 43.01,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.87,
        "relativeSystemComplexity": 5.87,
        "totalStructuralComplexity": 20,
        "totalDataComplexity": 9.33,
        "totalSystemComplexity": 29.33,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "numberOfUnitTests": 3,
        "violations": {}
    },
    {
        "name": "Hal\\Component\\File\\Finder",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fetch",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "externals": [
            "RecursiveDirectoryIterator",
            "RecursiveIteratorIterator",
            "RegexIterator"
        ],
        "lcom": 1,
        "length": 64,
        "vocabulary": 25,
        "volume": 297.21,
        "difficulty": 4.38,
        "effort": 1302.05,
        "level": 0.23,
        "bugs": 0.1,
        "time": 72,
        "intelligentContent": 67.84,
        "number_operators": 18,
        "number_operands": 46,
        "number_operators_unique": 4,
        "number_operands_unique": 21,
        "cloc": 35,
        "loc": 68,
        "lloc": 33,
        "mi": 93.84,
        "mIwoC": 49.02,
        "commentWeight": 44.82,
        "kanDefect": 0.68,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 6,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Violation\\Violations",
        "interface": false,
        "methods": [
            {
                "name": "getIterator",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "count",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "__toString",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "externals": [
            "IteratorAggregate",
            "Countable",
            "ArrayIterator",
            "Hal\\Violation\\Violation"
        ],
        "lcom": 1,
        "length": 20,
        "vocabulary": 9,
        "volume": 63.4,
        "difficulty": 5.2,
        "effort": 329.67,
        "level": 0.19,
        "bugs": 0.02,
        "time": 18,
        "intelligentContent": 12.19,
        "number_operators": 7,
        "number_operands": 13,
        "number_operators_unique": 4,
        "number_operands_unique": 5,
        "cloc": 19,
        "loc": 44,
        "lloc": 25,
        "mi": 99.17,
        "mIwoC": 56.62,
        "commentWeight": 42.55,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.63,
        "relativeSystemComplexity": 2.63,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 6.5,
        "totalSystemComplexity": 10.5,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "numberOfUnitTests": 1,
        "violations": {}
    },
    {
        "name": "Hal\\Violation\\Class_\\Blob",
        "interface": false,
        "methods": [
            {
                "name": "getName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apply",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLevel",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDescription",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 6,
        "externals": [
            "Hal\\Violation\\Violation",
            "Hal\\Metric\\Metric"
        ],
        "lcom": 3,
        "length": 47,
        "vocabulary": 19,
        "volume": 199.65,
        "difficulty": 4.27,
        "effort": 851.85,
        "level": 0.23,
        "bugs": 0.07,
        "time": 47,
        "intelligentContent": 46.79,
        "number_operators": 15,
        "number_operands": 32,
        "number_operators_unique": 4,
        "number_operands_unique": 15,
        "cloc": 12,
        "loc": 56,
        "lloc": 42,
        "mi": 80.54,
        "mIwoC": 47.68,
        "commentWeight": 32.86,
        "kanDefect": 0.5,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.42,
        "relativeSystemComplexity": 5.42,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 5.67,
        "totalSystemComplexity": 21.67,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "numberOfUnitTests": 1,
        "violations": {}
    },
    {
        "name": "Hal\\Violation\\Class_\\TooComplexCode",
        "interface": false,
        "methods": [
            {
                "name": "getName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apply",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLevel",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDescription",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "externals": [
            "Hal\\Violation\\Violation",
            "Hal\\Metric\\Metric"
        ],
        "lcom": 3,
        "length": 28,
        "vocabulary": 15,
        "volume": 109.39,
        "difficulty": 3.45,
        "effort": 377.9,
        "level": 0.29,
        "bugs": 0.04,
        "time": 21,
        "intelligentContent": 31.67,
        "number_operators": 9,
        "number_operands": 19,
        "number_operators_unique": 4,
        "number_operands_unique": 11,
        "cloc": 12,
        "loc": 46,
        "lloc": 32,
        "mi": 88.05,
        "mIwoC": 52.49,
        "commentWeight": 35.56,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.75,
        "relativeSystemComplexity": 5.75,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 23,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Violation\\Class_\\TooDependent",
        "interface": false,
        "methods": [
            {
                "name": "getName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apply",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLevel",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDescription",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "externals": [
            "Hal\\Violation\\Violation",
            "Hal\\Metric\\Metric"
        ],
        "lcom": 3,
        "length": 28,
        "vocabulary": 14,
        "volume": 106.61,
        "difficulty": 3.8,
        "effort": 405.1,
        "level": 0.26,
        "bugs": 0.04,
        "time": 23,
        "intelligentContent": 28.05,
        "number_operators": 9,
        "number_operands": 19,
        "number_operators_unique": 4,
        "number_operands_unique": 10,
        "cloc": 12,
        "loc": 45,
        "lloc": 31,
        "mi": 88.73,
        "mIwoC": 52.87,
        "commentWeight": 35.87,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.75,
        "relativeSystemComplexity": 5.75,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 23,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Violation\\Class_\\TooLong",
        "interface": false,
        "methods": [
            {
                "name": "getName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apply",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLevel",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDescription",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "externals": [
            "Hal\\Violation\\Violation",
            "Hal\\Metric\\Metric"
        ],
        "lcom": 3,
        "length": 27,
        "vocabulary": 15,
        "volume": 105.49,
        "difficulty": 3.45,
        "effort": 364.41,
        "level": 0.29,
        "bugs": 0.04,
        "time": 20,
        "intelligentContent": 30.54,
        "number_operators": 8,
        "number_operands": 19,
        "number_operators_unique": 4,
        "number_operands_unique": 11,
        "cloc": 12,
        "loc": 45,
        "lloc": 31,
        "mi": 88.77,
        "mIwoC": 52.9,
        "commentWeight": 35.87,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.42,
        "relativeSystemComplexity": 5.42,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 5.67,
        "totalSystemComplexity": 21.67,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Violation\\Class_\\ProbablyBugged",
        "interface": false,
        "methods": [
            {
                "name": "getName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apply",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getLevel",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDescription",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "externals": [
            "Hal\\Violation\\Violation",
            "Hal\\Metric\\Metric"
        ],
        "lcom": 3,
        "length": 31,
        "vocabulary": 17,
        "volume": 126.71,
        "difficulty": 3.23,
        "effort": 409.38,
        "level": 0.31,
        "bugs": 0.04,
        "time": 23,
        "intelligentContent": 39.22,
        "number_operators": 10,
        "number_operands": 21,
        "number_operators_unique": 4,
        "number_operands_unique": 13,
        "cloc": 13,
        "loc": 48,
        "lloc": 34,
        "mi": 87.55,
        "mIwoC": 51.46,
        "commentWeight": 36.08,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.75,
        "relativeSystemComplexity": 5.75,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 23,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Violation\\ViolationParser",
        "interface": false,
        "methods": [
            {
                "name": "apply",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "externals": [
            "Hal\\Metric\\Metrics",
            "Hal\\Violation\\Class_\\Blob",
            "Hal\\Violation\\Class_\\TooComplexCode",
            "Hal\\Violation\\Class_\\ProbablyBugged",
            "Hal\\Violation\\Class_\\TooLong",
            "Hal\\Violation\\Class_\\TooDependent",
            "Hal\\Violation\\Violations"
        ],
        "lcom": 1,
        "length": 13,
        "vocabulary": 7,
        "volume": 36.5,
        "difficulty": 2.2,
        "effort": 80.29,
        "level": 0.45,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 16.59,
        "number_operators": 2,
        "number_operands": 11,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 4,
        "loc": 19,
        "lloc": 15,
        "mi": 95.62,
        "mIwoC": 63,
        "commentWeight": 32.62,
        "kanDefect": 0.61,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 9.5,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 9.5,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 7,
        "instability": 0.88,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Application\\Analyze",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "externals": [
            "Hal\\Application\\Config\\Config",
            "Hal\\Component\\Output\\Output",
            "Hal\\Component\\Issue\\Issuer",
            "Hal\\Metric\\Metrics",
            "PhpParser\\ParserFactory",
            "Hal\\Component\\Ast\\NodeTraverser",
            "PhpParser\\NodeVisitor\\NameResolver",
            "Hal\\Metric\\Class_\\ClassEnumVisitor",
            "Hal\\Metric\\Class_\\Complexity\\CyclomaticComplexityVisitor",
            "Hal\\Metric\\Class_\\Coupling\\ExternalsVisitor",
            "Hal\\Metric\\Class_\\Structural\\LcomVisitor",
            "Hal\\Metric\\Class_\\Text\\HalsteadVisitor",
            "Hal\\Metric\\Class_\\Text\\LengthVisitor",
            "Hal\\Metric\\Class_\\Complexity\\CyclomaticComplexityVisitor",
            "Hal\\Metric\\Class_\\Component\\MaintainabilityIndexVisitor",
            "Hal\\Metric\\Class_\\Complexity\\KanDefectVisitor",
            "Hal\\Metric\\Class_\\Structural\\SystemComplexityVisitor",
            "Hal\\Component\\Output\\ProgressBar",
            "Hal\\Metric\\System\\Coupling\\PageRank",
            "Hal\\Metric\\System\\Coupling\\Coupling",
            "Hal\\Metric\\System\\Changes\\GitChanges",
            "Hal\\Metric\\System\\UnitTesting\\UnitTesting"
        ],
        "lcom": 1,
        "length": 88,
        "vocabulary": 21,
        "volume": 386.52,
        "difficulty": 6.25,
        "effort": 2415.77,
        "level": 0.16,
        "bugs": 0.13,
        "time": 134,
        "intelligentContent": 61.84,
        "number_operators": 13,
        "number_operands": 75,
        "number_operators_unique": 3,
        "number_operands_unique": 18,
        "cloc": 27,
        "loc": 86,
        "lloc": 59,
        "mi": 81.14,
        "mIwoC": 42.99,
        "commentWeight": 38.15,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.36,
        "relativeSystemComplexity": 100.36,
        "totalStructuralComplexity": 200,
        "totalDataComplexity": 0.73,
        "totalSystemComplexity": 200.73,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 22,
        "instability": 0.96,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Application\\Application",
        "interface": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "externals": [
            "Hal\\Component\\Output\\CliOutput",
            "Hal\\Component\\Issue\\Issuer",
            "Hal\\Application\\Config\\Parser",
            "Hal\\Application\\Config\\Validator",
            "Hal\\Application\\Config\\Validator",
            "Hal\\Application\\Config\\Validator",
            "Hal\\Component\\File\\Finder",
            "Hal\\Application\\Analyze",
            "Hal\\Violation\\ViolationParser",
            "Hal\\Report\\Cli\\Reporter",
            "Hal\\Report\\Html\\Reporter",
            "Hal\\Report\\Violations\\Xml\\Reporter"
        ],
        "lcom": 1,
        "length": 71,
        "vocabulary": 23,
        "volume": 321.17,
        "difficulty": 4.5,
        "effort": 1445.28,
        "level": 0.22,
        "bugs": 0.11,
        "time": 80,
        "intelligentContent": 71.37,
        "number_operators": 11,
        "number_operands": 60,
        "number_operators_unique": 3,
        "number_operands_unique": 20,
        "cloc": 13,
        "loc": 55,
        "lloc": 43,
        "mi": 80.74,
        "mIwoC": 46.55,
        "commentWeight": 34.2,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0.08,
        "relativeSystemComplexity": 144.08,
        "totalStructuralComplexity": 144,
        "totalDataComplexity": 0.08,
        "totalSystemComplexity": 144.08,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 12,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Application\\Config\\Validator",
        "interface": false,
        "methods": [
            {
                "name": "validate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "help",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 8,
        "externals": [
            "Hal\\Application\\Config\\Config",
            "Hal\\Application\\Config\\ConfigException",
            "Hal\\Application\\Config\\ConfigException",
            "Hal\\Application\\Config\\ConfigException"
        ],
        "lcom": 2,
        "length": 57,
        "vocabulary": 23,
        "volume": 257.84,
        "difficulty": 8.12,
        "effort": 2093.08,
        "level": 0.12,
        "bugs": 0.09,
        "time": 116,
        "intelligentContent": 31.76,
        "number_operators": 11,
        "number_operands": 46,
        "number_operators_unique": 6,
        "number_operands_unique": 17,
        "cloc": 15,
        "loc": 81,
        "lloc": 54,
        "mi": 75.17,
        "mIwoC": 44.25,
        "commentWeight": 30.92,
        "kanDefect": 0.96,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.38,
        "relativeSystemComplexity": 9.38,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0.75,
        "totalSystemComplexity": 18.75,
        "pageRank": 0,
        "afferentCoupling": 3,
        "efferentCoupling": 4,
        "instability": 0.57,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Application\\Config\\ConfigException",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 4,
        "efferentCoupling": 1,
        "instability": 0.2,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "Hal\\Application\\Config\\Parser",
        "interface": false,
        "methods": [
            {
                "name": "parse",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 8,
        "externals": [
            "Hal\\Application\\Config\\Config"
        ],
        "lcom": 1,
        "length": 67,
        "vocabulary": 23,
        "volume": 303.08,
        "difficulty": 9.18,
        "effort": 2781.19,
        "level": 0.11,
        "bugs": 0.1,
        "time": 155,
        "intelligentContent": 33.03,
        "number_operators": 15,
        "number_operands": 52,
        "number_operators_unique": 6,
        "number_operands_unique": 17,
        "cloc": 3,
        "loc": 36,
        "lloc": 33,
        "mi": 70.05,
        "mIwoC": 48.42,
        "commentWeight": 21.62,
        "kanDefect": 0.96,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 2.5,
        "pageRank": 0,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "numberOfUnitTests": 1,
        "violations": {}
    },
    {
        "name": "Hal\\Application\\Config\\Config",
        "interface": false,
        "methods": [
            {
                "name": "set",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "has",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "all",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "externals": [],
        "lcom": 1,
        "length": 29,
        "vocabulary": 6,
        "volume": 74.96,
        "difficulty": 5.75,
        "effort": 431.04,
        "level": 0.17,
        "bugs": 0.02,
        "time": 24,
        "intelligentContent": 13.04,
        "number_operators": 6,
        "number_operands": 23,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 23,
        "loc": 52,
        "lloc": 29,
        "mi": 97.58,
        "mIwoC": 54.7,
        "commentWeight": 42.87,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 6,
        "totalStructuralComplexity": 20,
        "totalDataComplexity": 10,
        "totalSystemComplexity": 30,
        "pageRank": 0.01,
        "afferentCoupling": 7,
        "efferentCoupling": 0,
        "instability": 0,
        "numberOfUnitTests": 0,
        "violations": {}
    },
    {
        "name": "MyVisitor",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "leaveNode",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "ccn": 1,
        "externals": [
            "PhpParser\\NodeVisitorAbstract",
            "PhpParser\\Node"
        ],
        "lcom": 1,
        "length": 7,
        "vocabulary": 4,
        "volume": 14,
        "difficulty": 1,
        "effort": 14,
        "level": 1,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 14,
        "number_operators": 1,
        "number_operands": 6,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 13,
        "loc": 26,
        "lloc": 13,
        "mi": 112,
        "mIwoC": 67.54,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "pageRank": 0,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "numberOfUnitTests": 0,
        "violations": {}
    }
]