var classes = [
    {
        "name": "Hal\\Report\\Html\\Reporter",
        "interface": false,
        "nbMethods": 4,
        "ccn": 14,
        "externals": [
            "Hal\\Application\\Config\\Config",
            "Symfony\\Component\\Console\\Output\\OutputInterface",
            "Hal\\Metric\\Metrics",
            "Hal\\Metric\\Consolidated",
            "Hal\\Metric\\Consolidated"
        ],
        "lcom": 1,
        "length": 332,
        "vocabulary": 86,
        "volume": 2133.52,
        "difficulty": 13.79,
        "effort": 29425.95,
        "level": 0.07,
        "bugs": 0.71,
        "time": 1635,
        "intelligentContent": 154.69,
        "number_operators": 96,
        "number_operands": 236,
        "number_operators_unique": 9,
        "number_operands_unique": 77,
        "cloc": 30,
        "loc": 142,
        "lloc": 115,
        "mi": 62.52,
        "mIwoC": 29.85,
        "commentWeight": 32.67,
        "kanDefect": 1.15,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.68,
        "relativeSystemComplexity": 81.68,
        "totalStructuralComplexity": 324,
        "totalDataComplexity": 2.7,
        "totalSystemComplexity": 326.7,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83
    },
    {
        "name": "Hal\\Report\\Cli\\Reporter",
        "interface": false,
        "nbMethods": 2,
        "ccn": 8,
        "externals": [
            "Hal\\Application\\Config\\Config",
            "Symfony\\Component\\Console\\Output\\OutputInterface",
            "Hal\\Metric\\Metrics",
            "Hal\\Metric\\Consolidated"
        ],
        "lcom": 1,
        "length": 141,
        "vocabulary": 54,
        "volume": 811.44,
        "difficulty": 8.19,
        "effort": 6646.9,
        "level": 0.12,
        "bugs": 0.27,
        "time": 369,
        "intelligentContent": 99.06,
        "number_operators": 31,
        "number_operands": 110,
        "number_operators_unique": 7,
        "number_operands_unique": 47,
        "cloc": 13,
        "loc": 90,
        "lloc": 72,
        "mi": 65.81,
        "mIwoC": 38.04,
        "commentWeight": 27.77,
        "kanDefect": 0.96,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.42,
        "relativeSystemComplexity": 25.42,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 0.83,
        "totalSystemComplexity": 50.83,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8
    },
    {
        "name": "Hal\\Metric\\Consolidated",
        "interface": false,
        "nbMethods": 6,
        "ccn": 11,
        "externals": [
            "Hal\\Metric\\Metrics"
        ],
        "lcom": 1,
        "length": 144,
        "vocabulary": 41,
        "volume": 771.49,
        "difficulty": 10.91,
        "effort": 8418.29,
        "level": 0.09,
        "bugs": 0.26,
        "time": 468,
        "intelligentContent": 70.7,
        "number_operators": 38,
        "number_operands": 106,
        "number_operators_unique": 7,
        "number_operands_unique": 34,
        "cloc": 36,
        "loc": 115,
        "lloc": 79,
        "mi": 75.02,
        "mIwoC": 36.91,
        "commentWeight": 38.11,
        "kanDefect": 1.49,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.72,
        "relativeSystemComplexity": 5.72,
        "totalStructuralComplexity": 24,
        "totalDataComplexity": 10.33,
        "totalSystemComplexity": 34.33,
        "pageRank": 0.01,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25
    },
    {
        "name": "Hal\\Metric\\InterfaceMetric",
        "interface": false,
        "nbMethods": 0,
        "ccn": 1,
        "externals": [
            "Hal\\Metric\\ClassMetric"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5
    },
    {
        "name": "Hal\\Metric\\FunctionMetric",
        "interface": false,
        "nbMethods": 0,
        "ccn": 1,
        "externals": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 3,
        "efferentCoupling": 0,
        "instability": 0
    },
    {
        "name": "Hal\\Metric\\FileMetric",
        "interface": false,
        "nbMethods": 0,
        "ccn": 1,
        "externals": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0
    },
    {
        "name": "Hal\\Metric\\Metrics",
        "interface": false,
        "nbMethods": 4,
        "ccn": 1,
        "externals": [],
        "lcom": 1,
        "length": 19,
        "vocabulary": 5,
        "volume": 44.12,
        "difficulty": 4.67,
        "effort": 205.88,
        "level": 0.21,
        "bugs": 0.01,
        "time": 11,
        "intelligentContent": 9.45,
        "number_operators": 5,
        "number_operands": 14,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 22,
        "loc": 44,
        "lloc": 22,
        "mi": 103.52,
        "mIwoC": 59.07,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.58,
        "relativeSystemComplexity": 5.58,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 6.33,
        "totalSystemComplexity": 22.33,
        "pageRank": 0.03,
        "afferentCoupling": 16,
        "efferentCoupling": 0,
        "instability": 0
    },
    {
        "name": "Hal\\Metric\\ProjectMetric",
        "interface": false,
        "nbMethods": 0,
        "ccn": 1,
        "externals": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0
    },
    {
        "name": "Hal\\Metric\\Class_\\Component\\MaintainabilityIndexVisitor",
        "interface": false,
        "nbMethods": 2,
        "ccn": 10,
        "externals": [
            "PhpParser\\NodeVisitorAbstract",
            "Hal\\Metric\\Metrics",
            "PhpParser\\Node",
            "Hal\\Metric\\FunctionMetric",
            "LogicException",
            "LogicException",
            "LogicException",
            "LogicException",
            "LogicException"
        ],
        "lcom": 1,
        "length": 111,
        "vocabulary": 36,
        "volume": 573.86,
        "difficulty": 10.14,
        "effort": 5820.6,
        "level": 0.1,
        "bugs": 0.19,
        "time": 323,
        "intelligentContent": 56.58,
        "number_operators": 40,
        "number_operands": 71,
        "number_operators_unique": 8,
        "number_operands_unique": 28,
        "cloc": 31,
        "loc": 77,
        "lloc": 46,
        "mi": 84.67,
        "mIwoC": 43.07,
        "commentWeight": 41.61,
        "kanDefect": 0.78,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.2,
        "relativeSystemComplexity": 16.2,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 0.4,
        "totalSystemComplexity": 32.4,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 9,
        "instability": 0.9
    },
    {
        "name": "Hal\\Metric\\Class_\\Coupling\\ExternalsVisitor",
        "interface": false,
        "nbMethods": 2,
        "ccn": 14,
        "externals": [
            "PhpParser\\NodeVisitorAbstract",
            "Hal\\Metric\\Metrics",
            "PhpParser\\Node"
        ],
        "lcom": 1,
        "length": 67,
        "vocabulary": 15,
        "volume": 261.76,
        "difficulty": 9.64,
        "effort": 2522.43,
        "level": 0.1,
        "bugs": 0.09,
        "time": 140,
        "intelligentContent": 27.16,
        "number_operators": 14,
        "number_operands": 53,
        "number_operators_unique": 4,
        "number_operands_unique": 11,
        "cloc": 22,
        "loc": 79,
        "lloc": 57,
        "mi": 79.36,
        "mIwoC": 42.88,
        "commentWeight": 36.47,
        "kanDefect": 1.92,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 9.25,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 18.5,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75
    },
    {
        "name": "Hal\\Metric\\Class_\\Text\\HalsteadVisitor",
        "interface": false,
        "nbMethods": 2,
        "ccn": 4,
        "externals": [
            "PhpParser\\NodeVisitorAbstract",
            "Hal\\Metric\\Metrics",
            "PhpParser\\Node",
            "Hal\\Metric\\FunctionMetric"
        ],
        "lcom": 1,
        "length": 218,
        "vocabulary": 50,
        "volume": 1230.36,
        "difficulty": 11.97,
        "effort": 14721.41,
        "level": 0.08,
        "bugs": 0.41,
        "time": 818,
        "intelligentContent": 102.83,
        "number_operators": 71,
        "number_operands": 147,
        "number_operators_unique": 7,
        "number_operands_unique": 43,
        "cloc": 29,
        "loc": 88,
        "lloc": 59,
        "mi": 78.03,
        "mIwoC": 39.2,
        "commentWeight": 38.83,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.2,
        "relativeSystemComplexity": 16.2,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 0.4,
        "totalSystemComplexity": 32.4,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8
    },
    {
        "name": "Hal\\Metric\\Class_\\Text\\LengthVisitor",
        "interface": false,
        "nbMethods": 2,
        "ccn": 5,
        "externals": [
            "PhpParser\\NodeVisitorAbstract",
            "Hal\\Metric\\Metrics",
            "PhpParser\\Node",
            "Hal\\Metric\\FunctionMetric",
            "PhpParser\\PrettyPrinter\\Standard"
        ],
        "lcom": 1,
        "length": 80,
        "vocabulary": 25,
        "volume": 371.51,
        "difficulty": 7.75,
        "effort": 2879.19,
        "level": 0.13,
        "bugs": 0.12,
        "time": 160,
        "intelligentContent": 47.94,
        "number_operators": 18,
        "number_operands": 62,
        "number_operators_unique": 5,
        "number_operands_unique": 20,
        "cloc": 20,
        "loc": 55,
        "lloc": 36,
        "mi": 87.59,
        "mIwoC": 47.38,
        "commentWeight": 40.21,
        "kanDefect": 0.59,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.17,
        "relativeSystemComplexity": 25.17,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 50.33,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83
    },
    {
        "name": "Hal\\Metric\\Class_\\Complexity\\KanDefectVisitor",
        "interface": false,
        "nbMethods": 2,
        "ccn": 2,
        "externals": [
            "PhpParser\\NodeVisitorAbstract",
            "Hal\\Metric\\Metrics",
            "PhpParser\\Node"
        ],
        "lcom": 1,
        "length": 50,
        "vocabulary": 21,
        "volume": 219.62,
        "difficulty": 7,
        "effort": 1537.31,
        "level": 0.14,
        "bugs": 0.07,
        "time": 85,
        "intelligentContent": 31.37,
        "number_operators": 15,
        "number_operands": 35,
        "number_operators_unique": 6,
        "number_operands_unique": 15,
        "cloc": 15,
        "loc": 48,
        "lloc": 33,
        "mi": 88.3,
        "mIwoC": 50.21,
        "commentWeight": 38.09,
        "kanDefect": 0.44,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 9.25,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 18.5,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75
    },
    {
        "name": "Hal\\Metric\\Class_\\Complexity\\CyclomaticComplexityVisitor",
        "interface": false,
        "nbMethods": 2,
        "ccn": 4,
        "externals": [
            "PhpParser\\NodeVisitorAbstract",
            "Hal\\Metric\\Metrics",
            "PhpParser\\Node"
        ],
        "lcom": 1,
        "length": 68,
        "vocabulary": 19,
        "volume": 288.86,
        "difficulty": 18.91,
        "effort": 5462.06,
        "level": 0.05,
        "bugs": 0.1,
        "time": 303,
        "intelligentContent": 15.28,
        "number_operators": 16,
        "number_operands": 52,
        "number_operators_unique": 8,
        "number_operands_unique": 11,
        "cloc": 27,
        "loc": 80,
        "lloc": 53,
        "mi": 83.79,
        "mIwoC": 44.62,
        "commentWeight": 39.17,
        "kanDefect": 1.04,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 9.5,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 19,
        "pageRank": 0.01,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6
    },
    {
        "name": "Hal\\Metric\\Class_\\ClassEnumVisitor",
        "interface": false,
        "nbMethods": 2,
        "ccn": 5,
        "externals": [
            "PhpParser\\NodeVisitorAbstract",
            "Hal\\Metric\\Metrics",
            "PhpParser\\Node",
            "Hal\\Metric\\InterfaceMetric",
            "Hal\\Metric\\ClassMetric"
        ],
        "lcom": 1,
        "length": 37,
        "vocabulary": 13,
        "volume": 136.92,
        "difficulty": 4.35,
        "effort": 595.59,
        "level": 0.23,
        "bugs": 0.05,
        "time": 33,
        "intelligentContent": 31.48,
        "number_operators": 8,
        "number_operands": 29,
        "number_operators_unique": 3,
        "number_operands_unique": 10,
        "cloc": 7,
        "loc": 37,
        "lloc": 30,
        "mi": 83.35,
        "mIwoC": 52.15,
        "commentWeight": 31.2,
        "kanDefect": 0.59,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 9.25,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 18.5,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83
    },
    {
        "name": "Hal\\Metric\\Class_\\Structural\\SystemComplexityVisitor",
        "interface": false,
        "nbMethods": 2,
        "ccn": 4,
        "externals": [
            "PhpParser\\NodeVisitorAbstract",
            "Hal\\Metric\\Metrics",
            "PhpParser\\Node"
        ],
        "lcom": 1,
        "length": 98,
        "vocabulary": 27,
        "volume": 465.98,
        "difficulty": 8.3,
        "effort": 3865.51,
        "level": 0.12,
        "bugs": 0.16,
        "time": 215,
        "intelligentContent": 56.17,
        "number_operators": 25,
        "number_operands": 73,
        "number_operators_unique": 5,
        "number_operands_unique": 22,
        "cloc": 23,
        "loc": 63,
        "lloc": 40,
        "mi": 86.09,
        "mIwoC": 45.83,
        "commentWeight": 40.26,
        "kanDefect": 0.74,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 9.25,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 18.5,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75
    },
    {
        "name": "Hal\\Metric\\Class_\\Structural\\LcomVisitor",
        "interface": false,
        "nbMethods": 3,
        "ccn": 8,
        "externals": [
            "PhpParser\\NodeVisitorAbstract",
            "Hal\\Metric\\Metrics",
            "PhpParser\\Node",
            "Hal\\Component\\Tree\\Graph",
            "Hal\\Component\\Tree\\Node",
            "Hal\\Component\\Tree\\Node",
            "Hal\\Component\\Tree\\Node",
            "Hal\\Component\\Tree\\Node"
        ],
        "lcom": 1,
        "length": 111,
        "vocabulary": 23,
        "volume": 502.12,
        "difficulty": 20.53,
        "effort": 10310.1,
        "level": 0.05,
        "bugs": 0.17,
        "time": 573,
        "intelligentContent": 24.45,
        "number_operators": 34,
        "number_operands": 77,
        "number_operators_unique": 8,
        "number_operands_unique": 15,
        "cloc": 27,
        "loc": 89,
        "lloc": 62,
        "mi": 78.59,
        "mIwoC": 40.91,
        "commentWeight": 37.67,
        "kanDefect": 1.47,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 81.5,
        "totalStructuralComplexity": 243,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 244.5,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 8,
        "instability": 0.89
    },
    {
        "name": "Hal\\Metric\\System\\Changes\\GitChanges",
        "interface": false,
        "nbMethods": 3,
        "ccn": 14,
        "externals": [
            "Hal\\Application\\Config\\Config",
            "Hal\\Metric\\Metrics",
            "Hal\\Application\\Config\\ConfigException",
            "DateTime",
            "Hal\\Metric\\ProjectMetric",
            "Hal\\Metric\\FileMetric"
        ],
        "lcom": 1,
        "length": 256,
        "vocabulary": 49,
        "volume": 1437.37,
        "difficulty": 16.17,
        "effort": 23237.41,
        "level": 0.06,
        "bugs": 0.48,
        "time": 1291,
        "intelligentContent": 88.91,
        "number_operators": 62,
        "number_operands": 194,
        "number_operators_unique": 7,
        "number_operands_unique": 42,
        "cloc": 36,
        "loc": 142,
        "lloc": 106,
        "mi": 66.99,
        "mIwoC": 31.83,
        "commentWeight": 35.17,
        "kanDefect": 1.82,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.54,
        "relativeSystemComplexity": 49.54,
        "totalStructuralComplexity": 147,
        "totalDataComplexity": 1.63,
        "totalSystemComplexity": 148.63,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 6,
        "instability": 0.86
    },
    {
        "name": "Hal\\Metric\\System\\Coupling\\PageRank",
        "interface": false,
        "nbMethods": 2,
        "ccn": 12,
        "externals": [
            "Hal\\Metric\\Metrics"
        ],
        "lcom": 1,
        "length": 136,
        "vocabulary": 40,
        "volume": 723.78,
        "difficulty": 24.31,
        "effort": 17598.63,
        "level": 0.04,
        "bugs": 0.24,
        "time": 978,
        "intelligentContent": 29.77,
        "number_operators": 35,
        "number_operands": 101,
        "number_operators_unique": 13,
        "number_operands_unique": 27,
        "cloc": 20,
        "loc": 75,
        "lloc": 55,
        "mi": 76.27,
        "mIwoC": 40.4,
        "commentWeight": 35.87,
        "kanDefect": 2.13,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 16.5,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 33,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5
    },
    {
        "name": "Hal\\Metric\\System\\Coupling\\Coupling",
        "interface": false,
        "nbMethods": 1,
        "ccn": 14,
        "externals": [
            "Hal\\Metric\\Metrics",
            "Hal\\Component\\Tree\\Graph",
            "Hal\\Component\\Tree\\Node",
            "Hal\\Component\\Tree\\Node"
        ],
        "lcom": 1,
        "length": 84,
        "vocabulary": 23,
        "volume": 379.98,
        "difficulty": 11.12,
        "effort": 4224.47,
        "level": 0.09,
        "bugs": 0.13,
        "time": 235,
        "intelligentContent": 34.18,
        "number_operators": 21,
        "number_operands": 63,
        "number_operators_unique": 6,
        "number_operands_unique": 17,
        "cloc": 12,
        "loc": 56,
        "lloc": 44,
        "mi": 77.06,
        "mIwoC": 44.2,
        "commentWeight": 32.86,
        "kanDefect": 1.56,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.09,
        "relativeSystemComplexity": 100.09,
        "totalStructuralComplexity": 100,
        "totalDataComplexity": 0.09,
        "totalSystemComplexity": 100.09,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8
    },
    {
        "name": "Hal\\Metric\\ClassMetric",
        "interface": false,
        "nbMethods": 0,
        "ccn": 1,
        "externals": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0
    },
    {
        "name": "Hal\\Component\\Tree\\Edge",
        "interface": false,
        "nbMethods": 4,
        "ccn": 1,
        "externals": [
            "Hal\\Component\\Tree\\Node",
            "Hal\\Component\\Tree\\Node"
        ],
        "lcom": 1,
        "length": 16,
        "vocabulary": 6,
        "volume": 41.36,
        "difficulty": 2.75,
        "effort": 113.74,
        "level": 0.36,
        "bugs": 0.01,
        "time": 6,
        "intelligentContent": 15.04,
        "number_operators": 5,
        "number_operands": 11,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 23,
        "loc": 47,
        "lloc": 24,
        "mi": 102.62,
        "mIwoC": 58.44,
        "commentWeight": 44.19,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.75,
        "relativeSystemComplexity": 2.75,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 11,
        "pageRank": 0.38,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5
    },
    {
        "name": "Hal\\Component\\Tree\\Node",
        "interface": false,
        "nbMethods": 7,
        "ccn": 4,
        "externals": [
            "Hal\\Component\\Tree\\Edge"
        ],
        "lcom": 1,
        "length": 47,
        "vocabulary": 9,
        "volume": 148.99,
        "difficulty": 12.4,
        "effort": 1847.43,
        "level": 0.08,
        "bugs": 0.05,
        "time": 103,
        "intelligentContent": 12.02,
        "number_operators": 16,
        "number_operands": 31,
        "number_operators_unique": 4,
        "number_operands_unique": 5,
        "cloc": 40,
        "loc": 89,
        "lloc": 49,
        "mi": 90.46,
        "mIwoC": 47.38,
        "commentWeight": 43.08,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.64,
        "relativeSystemComplexity": 10.64,
        "totalStructuralComplexity": 63,
        "totalDataComplexity": 11.5,
        "totalSystemComplexity": 74.5,
        "pageRank": 0.38,
        "afferentCoupling": 13,
        "efferentCoupling": 1,
        "instability": 0.07
    },
    {
        "name": "Hal\\Component\\Tree\\Graph",
        "interface": false,
        "nbMethods": 8,
        "ccn": 6,
        "externals": [
            "Countable",
            "Hal\\Component\\Tree\\Node",
            "Hal\\Component\\Tree\\GraphException",
            "Hal\\Component\\Tree\\Node",
            "Hal\\Component\\Tree\\Node",
            "Hal\\Component\\Tree\\GraphException",
            "Hal\\Component\\Tree\\GraphException",
            "Hal\\Component\\Tree\\Edge"
        ],
        "lcom": 1,
        "length": 67,
        "vocabulary": 16,
        "volume": 268,
        "difficulty": 8.5,
        "effort": 2278,
        "level": 0.12,
        "bugs": 0.09,
        "time": 127,
        "intelligentContent": 31.53,
        "number_operators": 16,
        "number_operands": 51,
        "number_operators_unique": 4,
        "number_operands_unique": 12,
        "cloc": 35,
        "loc": 94,
        "lloc": 59,
        "mi": 84.1,
        "mIwoC": 43.56,
        "commentWeight": 40.53,
        "kanDefect": 0.82,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 1.23,
        "relativeSystemComplexity": 37.23,
        "totalStructuralComplexity": 288,
        "totalDataComplexity": 9.86,
        "totalSystemComplexity": 297.86,
        "pageRank": 0.01,
        "afferentCoupling": 3,
        "efferentCoupling": 8,
        "instability": 0.73
    },
    {
        "name": "Hal\\Component\\Tree\\Operator\\CycleDetector",
        "interface": false,
        "nbMethods": 2,
        "ccn": 9,
        "externals": [
            "Hal\\Component\\Tree\\Graph",
            "Hal\\Component\\Tree\\Node"
        ],
        "lcom": 1,
        "length": 64,
        "vocabulary": 12,
        "volume": 229.44,
        "difficulty": 14.29,
        "effort": 3277.68,
        "level": 0.07,
        "bugs": 0.08,
        "time": 182,
        "intelligentContent": 16.06,
        "number_operators": 24,
        "number_operands": 40,
        "number_operators_unique": 5,
        "number_operands_unique": 7,
        "cloc": 23,
        "loc": 64,
        "lloc": 41,
        "mi": 87.12,
        "mIwoC": 47.08,
        "commentWeight": 40.04,
        "kanDefect": 1.12,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.79,
        "relativeSystemComplexity": 36.79,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 1.57,
        "totalSystemComplexity": 73.57,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1
    },
    {
        "name": "Hal\\Component\\Tree\\GraphException",
        "interface": false,
        "nbMethods": 0,
        "ccn": 1,
        "externals": [
            "LogicException"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25
    },
    {
        "name": "Hal\\Component\\Tree\\HashMap",
        "interface": false,
        "nbMethods": 5,
        "ccn": 1,
        "externals": [
            "Countable",
            "IteratorAggregate",
            "Hal\\Component\\Tree\\Node",
            "ArrayIterator"
        ],
        "lcom": 1,
        "length": 21,
        "vocabulary": 5,
        "volume": 48.76,
        "difficulty": 5,
        "effort": 243.8,
        "level": 0.2,
        "bugs": 0.02,
        "time": 14,
        "intelligentContent": 9.75,
        "number_operators": 6,
        "number_operands": 15,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 21,
        "loc": 47,
        "lloc": 26,
        "mi": 100.19,
        "mIwoC": 57.18,
        "commentWeight": 43.01,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.87,
        "relativeSystemComplexity": 5.87,
        "totalStructuralComplexity": 20,
        "totalDataComplexity": 9.33,
        "totalSystemComplexity": 29.33,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1
    },
    {
        "name": "Hal\\Component\\File\\Finder",
        "interface": false,
        "nbMethods": 2,
        "ccn": 4,
        "externals": [
            "RecursiveDirectoryIterator",
            "RecursiveIteratorIterator",
            "RegexIterator"
        ],
        "lcom": 1,
        "length": 64,
        "vocabulary": 25,
        "volume": 297.21,
        "difficulty": 4.38,
        "effort": 1302.05,
        "level": 0.23,
        "bugs": 0.1,
        "time": 72,
        "intelligentContent": 67.84,
        "number_operators": 18,
        "number_operands": 46,
        "number_operators_unique": 4,
        "number_operands_unique": 21,
        "cloc": 35,
        "loc": 68,
        "lloc": 33,
        "mi": 93.84,
        "mIwoC": 49.02,
        "commentWeight": 44.82,
        "kanDefect": 0.68,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 6,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75
    },
    {
        "name": "Hal\\Application\\Analyze",
        "interface": false,
        "nbMethods": 2,
        "ccn": 2,
        "externals": [
            "Hal\\Application\\Config\\Config",
            "Symfony\\Component\\Console\\Output\\OutputInterface",
            "Hal\\Metric\\Metrics",
            "PhpParser\\ParserFactory",
            "PhpParser\\NodeTraverser",
            "PhpParser\\NodeVisitor\\NameResolver",
            "Hal\\Metric\\Class_\\ClassEnumVisitor",
            "Hal\\Metric\\Class_\\Complexity\\CyclomaticComplexityVisitor",
            "Hal\\Metric\\Class_\\Coupling\\ExternalsVisitor",
            "Hal\\Metric\\Class_\\Structural\\LcomVisitor",
            "Hal\\Metric\\Class_\\Text\\HalsteadVisitor",
            "Hal\\Metric\\Class_\\Text\\LengthVisitor",
            "Hal\\Metric\\Class_\\Complexity\\CyclomaticComplexityVisitor",
            "Hal\\Metric\\Class_\\Component\\MaintainabilityIndexVisitor",
            "Hal\\Metric\\Class_\\Complexity\\KanDefectVisitor",
            "Hal\\Metric\\Class_\\Structural\\SystemComplexityVisitor",
            "Symfony\\Component\\Console\\Helper\\ProgressBar",
            "Hal\\Metric\\System\\Coupling\\PageRank",
            "Hal\\Metric\\System\\Coupling\\Coupling",
            "Hal\\Metric\\System\\Changes\\GitChanges"
        ],
        "lcom": 1,
        "length": 69,
        "vocabulary": 17,
        "volume": 282.03,
        "difficulty": 6.32,
        "effort": 1782.86,
        "level": 0.16,
        "bugs": 0.09,
        "time": 99,
        "intelligentContent": 44.62,
        "number_operators": 10,
        "number_operands": 59,
        "number_operators_unique": 3,
        "number_operands_unique": 14,
        "cloc": 22,
        "loc": 72,
        "lloc": 50,
        "mi": 83.29,
        "mIwoC": 45.51,
        "commentWeight": 37.77,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.21,
        "relativeSystemComplexity": 121.21,
        "totalStructuralComplexity": 242,
        "totalDataComplexity": 0.42,
        "totalSystemComplexity": 242.42,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 20,
        "instability": 0.95
    },
    {
        "name": "Hal\\Application\\Application",
        "interface": false,
        "nbMethods": 1,
        "ccn": 2,
        "externals": [
            "Symfony\\Component\\Console\\Formatter\\OutputFormatter",
            "Symfony\\Component\\Console\\Output\\ConsoleOutput",
            "Hal\\Application\\Config\\Parser",
            "Hal\\Application\\Config\\Validator",
            "Hal\\Application\\Config\\Validator",
            "Hal\\Application\\Config\\Validator",
            "Hal\\Component\\File\\Finder",
            "Hal\\Application\\Analyze",
            "Hal\\Report\\Cli\\Reporter",
            "Hal\\Report\\Html\\Reporter"
        ],
        "lcom": 1,
        "length": 55,
        "vocabulary": 19,
        "volume": 233.64,
        "difficulty": 4.22,
        "effort": 985.65,
        "level": 0.24,
        "bugs": 0.08,
        "time": 55,
        "intelligentContent": 55.38,
        "number_operators": 10,
        "number_operands": 45,
        "number_operators_unique": 3,
        "number_operands_unique": 16,
        "cloc": 10,
        "loc": 48,
        "lloc": 39,
        "mi": 80.92,
        "mIwoC": 48.44,
        "commentWeight": 32.48,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.08,
        "relativeSystemComplexity": 121.08,
        "totalStructuralComplexity": 121,
        "totalDataComplexity": 0.08,
        "totalSystemComplexity": 121.08,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 10,
        "instability": 1
    },
    {
        "name": "Hal\\Application\\Config\\Validator",
        "interface": false,
        "nbMethods": 2,
        "ccn": 4,
        "externals": [
            "Hal\\Application\\Config\\Config",
            "Hal\\Application\\Config\\ConfigException",
            "Hal\\Application\\Config\\ConfigException"
        ],
        "lcom": 2,
        "length": 14,
        "vocabulary": 8,
        "volume": 42,
        "difficulty": 1.83,
        "effort": 77,
        "level": 0.55,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 22.91,
        "number_operators": 3,
        "number_operands": 11,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 12,
        "loc": 48,
        "lloc": 30,
        "mi": 90.85,
        "mIwoC": 55.87,
        "commentWeight": 34.97,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 4.5,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 9,
        "pageRank": 0.01,
        "afferentCoupling": 3,
        "efferentCoupling": 3,
        "instability": 0.5
    },
    {
        "name": "Hal\\Application\\Config\\ConfigException",
        "interface": false,
        "nbMethods": 0,
        "ccn": 1,
        "externals": [
            "Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25
    },
    {
        "name": "Hal\\Application\\Config\\Parser",
        "interface": false,
        "nbMethods": 1,
        "ccn": 8,
        "externals": [
            "Hal\\Application\\Config\\Config"
        ],
        "lcom": 1,
        "length": 63,
        "vocabulary": 20,
        "volume": 272.28,
        "difficulty": 8.17,
        "effort": 2223.63,
        "level": 0.12,
        "bugs": 0.09,
        "time": 124,
        "intelligentContent": 33.34,
        "number_operators": 14,
        "number_operands": 49,
        "number_operators_unique": 5,
        "number_operands_unique": 15,
        "cloc": 3,
        "loc": 36,
        "lloc": 33,
        "mi": 70.37,
        "mIwoC": 48.75,
        "commentWeight": 21.62,
        "kanDefect": 0.96,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 2.5,
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5
    },
    {
        "name": "Hal\\Application\\Config\\Config",
        "interface": false,
        "nbMethods": 5,
        "ccn": 2,
        "externals": [],
        "lcom": 1,
        "length": 29,
        "vocabulary": 6,
        "volume": 74.96,
        "difficulty": 5.75,
        "effort": 431.04,
        "level": 0.17,
        "bugs": 0.02,
        "time": 24,
        "intelligentContent": 13.04,
        "number_operators": 6,
        "number_operands": 23,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 23,
        "loc": 52,
        "lloc": 29,
        "mi": 97.58,
        "mIwoC": 54.7,
        "commentWeight": 42.87,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 6,
        "totalStructuralComplexity": 20,
        "totalDataComplexity": 10,
        "totalSystemComplexity": 30,
        "pageRank": 0.02,
        "afferentCoupling": 6,
        "efferentCoupling": 0,
        "instability": 0
    }
]